app = "poket"
kill_signal = "SIGINT"
kill_timeout = 10
primary_region = "atl"
processes = []

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"
  initial_size = "1gb"

[build]

[build.args]
  PB_VERSION="0.21.2"

[env]

[experimental]
  auto_rollback = true
  allowed_public_ports = []

[[services]]
  http_checks = []
  internal_port = 8080
  # auto_stop_machines = true
  # auto_start_machines = true
  min_machines_running = 0  
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 2000
    soft_limit = 2000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
